#cloud-config
coreos:
  update:
    reboot-strategy: "best-effort"
  units:
    - name: coreos-cloudinit-mkdir.service
      command: start
      runtime: yes
      content: |
        [Service]
        Type=oneshot
        ExecStart=/bin/mkdir -p /var/lib/coreos-install
    - name: coreos-cloudinit-user-data.path
      command: start
      runtime: yes
      content: |
        [Path]
        PathExists=/var/lib/coreos-install/user-data
        Unit=user-cloudinit@var-lib-coreos\x2dinstall-user\x2ddata.service
    - name: change-motd.service
      commande: start
      runtime: yes
      content: |
        [Service]
        Type=oneshot
        EnvironmentFile=/etc/os-release
        ExecStartPre=/bin/sh -c '/usr/bin/sed -i -e \'/^CoreOS/d\' /etc/motd'
        ExecStart=/bin/sh -c '/usr/bin/sed -i -e \'$a CoreOS ${VERSION}\' /etc/motd'
  oem:
    id: aliyun
    name: xiucall-aliyun
    version-id: 1.0.0
    home-url: http://www.xiucall.com/
    bug-report-url: https://github.com/tuhuayuan/xiucall-cloud
