# This pod mounts the nfs volume claim into /usr/share/nginx/html and
# serves a simple web page.

apiVersion: v1
kind: ReplicationController
metadata:
  name: cache-master
spec:
  replicas: 1
  selector:
    role: cache-master
  template:
    metadata:
      labels:
        role: cache-master
    spec:
      containers:
      - name: redis
        image: index.tenxcloud.com/docker_library/redis:3
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: "/data"
      volumes:
      - name: redis-data
        emptyDir: {}
